### ISSUE TITLE
Allow header to scroll with persistent navigation

### ISSUE THREAD

**Issue by tallt0m** [colinsullivan/kagyumonlam.org#1]
Esp. in mobile, the header consumes a lot of screen height and does not scroll. This makes the content below the header less accessible for mobile users. 

However, if the entire page scrolls, the navigation will scroll with it -- and we want that to remain visible (?)

**Comment by colinsullivan** [comment]
fixed.

Lets do issues here: https://github.com/karmapa/kagyumonlam.org/issues
